### ISSUE TITLE
Description starts with empty words

### ISSUE THREAD

**Issue by colintedford** [AnAngryRaven/obsidian-open-sidebar-on-hover#1]
The words "Enables the ability to" that start the description convey no info because they apply to every plugin. Since "good descriptions often start with an action statement" ([Submission requirements for plugins](https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins#Keep+plugin+descriptions+short+and+simple)), "Open the sidebar by hovering over it" is enough.

Congratulations on the plugin release!

**Comment by AnAngryRaven** [comment]
Ack yes, you are right -- thought I had double checked the guidelines, but evidently not..

And thank you!! Definitely a little scarier when you have _other_ people using it as opposed to just yourself, but hopefully people can at least find it useful 🙂‍↕️
